# Site settings
title: APISENSE® — Middleware data visualization
email: contact@apisense.com
description: > # this means to ignore newlines until "baseurl:"
  APISENSE® makes it easy to collect data with crowds of mobile phone sensors. 
  Make sense and innovate on top of real world data feedback, in real time!.
baseurl: "/middleware2014" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: APISENSE
github_username:

# Build settings
markdown: kramdown
